FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

# RUN pip install scikit-learn
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./*.py /code
COPY ./app /code

RUN export PYTHONPATH=$PWD

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]